[package]
name = "wrangler"
version = "0.1.1"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "wrangle your workers, CLI for rustwasm Cloudflare workers!"
readme = "README.md"
categories = ["wasm"]
build = "build.rs"

[dependencies]
atty = "0.2.11"
binary-install = { git = "https://github.com/rustwasm/binary-install.git", rev = "3b13f9fb67e57789fae0c1c38e52de3f7c330b92" }
clap = "2.32.0"
config = "0.9.2"
console = "0.7.5"
dirs = "1.0.5"
env_logger = "0.6.1"
failure = "0.1.5"
log = "0.4.6"
openssl = { version = '0.10.11', optional = true }
reqwest = "0.9.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
toml = "0.5.0"
uuid = "0.7"
which = "2.0.1"
rand = "0.6.5"
walkdir = "2.2.7"
percent-encoding = "1.0.1"

[dev-dependencies]
assert_cmd = "0.11.1"
fs_extra = "1.1.0"

[features]
vendored-openssl = ['openssl/vendored']
