[package]
name = "wrangler"
version = "0.1.1"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "wrangle your workers, CLI for rustwasm Cloudflare workers!"
readme = "README.md"
categories = ["wasm"]

[dependencies]
binary-install = "0.0.2"
clap = "2.32.0"
config = "0.9.2"
console = "0.7.5"
dirs = "1.0.5"
env_logger = "0.6.1"
failure = "0.1.5"
log = "0.4.6"
openssl = { version = '0.10.11', optional = true }
reqwest = "0.9.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
toml = "0.5.0"
uuid = "0.7"
which = "2.0.1"

[features]
vendored-openssl = ['openssl/vendored']
